name: Publish packages to OSSRH

on:
  push:
    branches:
      - master
      - version-[0-9].[0-9]+.x
    tags:
      - v[0-9].[0-9]+.[0-9]+
  pull_request:

jobs:
  publish:
    uses: wavesplatform/protobuf-schemas/.github/workflows/mvn-publish.yml@5b4331ab892b44ad1fdd71862654421482dcd49c
    with:
      github-ref-name: ${{ github.ref_name }}
      github-event-number: ${{ github.event.number }}
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      OSSRH_GPG_KEY: ${{ secrets.OSSRH_GPG_KEY }}
      OSSRH_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
