name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - run: mvn -B test -Dmaven.test.failure.ignore=true
      - name: Publish test report
        uses: scacap/action-surefire-report@v1
